name = "susahsinyal" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2025-02-24"

[[routes]]
patteren = "sg1.susahsinyal.my.id"
custom_domain = true

[[routes]]
patteren = "space.byu.id.sg1.susahsinyal.my.id"
custom_domain = true

[[routes]]
patteren = "104.19.142.108.sg1.susahsinyal.my.id"
custom_domain = true

[[routes]]
patteren = "104.19.143.108.sg1.susahsinyal.my.id"
custom_domain = true

[[routes]]
patteren = "ruangguru.com.sg1.susahsinyal.my.id"
custom_domain = true

[[routes]]
patteren = "ir.huya.com.sg1.susahsinyal.my.id"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "01953714-2bc0-78ea-9c04-f2246161ecde"
